apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "rclone-secret"
  namespace: csi-rclone
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: rclone-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        remote: "seedbox"
        remotePath: ""
        configData: |
          [sftp_seedbox]
          type = ftp
          host = {{ .rclone_host }}
          user = {{ .rclone_user }}
          pass = {{ .rclone_pass }}
          explicit_tls = true

          [seedbox]
          type = sftp
          host = {{ .rclone_host }}
          user = {{ .rclone_user }}
          pass = {{ .rclone_pass }}
          shell_type = unix
  data:
    - secretKey: rclone_host
      remoteRef:
        key: rclone-seedbox
        property: host
    - secretKey: rclone_user
      remoteRef:
        key: rclone-seedbox
        property: user
    - secretKey: rclone_pass
      remoteRef:
        key: rclone-seedbox
        property: pass




