apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fritzbox-exporter-config
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: fritzbox-exporter-config
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        config.yaml: |
          exporter_port: 9787 # optional
          log_level: DEBUG # optional
          devices:
            - name: Fritz!Box 6660 Router
              hostname: 192.168.178.1
              username: {{ .username }}
              password: {{ .password }}
              host_info: True
  data:
    - secretKey: username
      remoteRef:
        key: fritzbox
        property: username
    - secretKey: password
      remoteRef:
        key: fritzbox
        property: password
