apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backup-github-creds
  namespace: openbao-backup
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: backup-github-creds
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: pat
      remoteRef:
        key: github
        property: pat
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backup-vaultwarden-creds
  namespace: openbao-backup
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: backup-vaultwarden-creds
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: email
      remoteRef:
        key: vaultwarden/backup-account
        property: email
    - secretKey: master_password
      remoteRef:
        key: vaultwarden/backup-account
        property: master_password
