apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bw-config
  namespace: openbao-backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
