{
  description = "Homelab development environment";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    peelbox = {
      url = "github:DiverOfDark/peelbox";
      flake = false;
    };
    appbahn = {
      url = "github:diverofdark/appbahn";
      flake = false;
    };
  };

  outputs = { self, nixpkgs, flake-utils, peelbox, appbahn }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; config.allowUnfree = true; };
        peelboxPkg = pkgs.rustPlatform.buildRustPackage {
          pname = "peelbox";
          version = "0.4.0";
          src = peelbox;
          cargoLock.lockFile = "${peelbox}/Cargo.lock";
          nativeBuildInputs = [ pkgs.pkg-config pkgs.protobuf ];
          buildInputs = [ pkgs.openssl pkgs.oniguruma ];
          OPENSSL_NO_VENDOR = 1;
          RUSTONIG_SYSTEM_LIBONIG = 1;
          doCheck = false;
        };
        appbahnPkg = pkgs.buildGoModule {
          pname = "appbahn";
          version = "0.1.0";
          src = "${appbahn}/cli";
          vendorHash = "sha256-l0A6g8Fc+ZU35n8HH98JntIi25CVOKnSVKCqforPETY=";
          postInstall = ''
            mv $out/bin/cli $out/bin/appbahn
          '';
        };
      in {
        packages.peelbox = peelboxPkg;
        packages.appbahn = appbahnPkg;
        packages.packer = pkgs.packer;

        devShells.default = pkgs.mkShell {
          name = "homelab";
          packages = [
            # Infrastructure as Code
            pkgs.opentofu
            pkgs.packer

            # Kubernetes
            pkgs.kubectl
            pkgs.kubectx
            pkgs.kubernetes-helm
            pkgs.talosctl
            pkgs.talhelper
            pkgs.argocd
            pkgs.k9s
            pkgs.krew
            pkgs.kubescape

            # Networking & service mesh
            pkgs.cilium-cli
            pkgs.hubble
            pkgs.cloudflared

            # Secrets & certs
            pkgs.sops
            pkgs.age
            pkgs.ssh-to-age
            pkgs.openbao
            pkgs.cmctl

            # Backup
            pkgs.velero

            # Cloud providers
            pkgs.hcloud

            # Container tooling
            peelboxPkg

            # AppBahn CLI
            appbahnPkg

            # Task runner
            pkgs.go-task

            # Utilities
            pkgs.yq
            pkgs.dos2unix
            pkgs.pre-commit
          ];
          shellHook = ''
            # Talos — config generated by talhelper
            export TALOSCONFIG=$PWD/talos/clusterconfig/talosconfig

            # OpenTofu / Kubernetes — override in_cluster_config for local use
            export BAO_ADDR=https://openbao.kirillorlov.pro
            export TF_VAR_openbao_token=`bao kv get -field=token secret/openbao/terraform`

            if [ -z "''${KUBERNETES_SERVICE_HOST:-}" ]; then
              # Local dev — use kubeconfig and override tofu backend
              export KUBE_CONFIG_PATH=~/.kube/config
              export TF_VAR_kube_config=~/.kube/config
              export TF_CLI_ARGS_init="-backend-config=$PWD/terraform/config.kubernetes.tfbackend"
            else
              # In-cluster (CI) — fetch age key from OpenBao for SOPS decryption
              export SOPS_AGE_KEY=$(bao kv get -field=age_key secret/talos/config)
            fi

            # ArgoCD
            export ARGOCD_SERVER=argo.kirillorlov.pro

            # Krew / virtctl
            export KREW_ROOT="''${KREW_ROOT:-$HOME/.krew}"
            export PATH="''${KREW_ROOT}/bin:$PATH"
            if ! kubectl krew list 2>/dev/null | grep -q virt; then
              kubectl krew install virt
            fi
            alias virtctl="kubectl virt"

            # Aliases
            alias k=kubectl
            alias t=tofu
            alias ta=talosctl

            # Shell completions
            source <(kubectl completion bash)
            source <(talosctl completion bash)
            source <(hcloud completion bash)

            echo ""
            echo "Homelab dev shell ready."
            echo "  IaC:        tofu, packer, talhelper"
            echo "  Kubernetes: kubectl, kubectx, helm, talosctl, argocd, k9s, kubescape"
            echo "  Network:    cilium, hubble, cloudflared"
            echo "  Secrets:    sops, age, bao, cmctl"
            echo "  Backup:     velero"
            echo "  Cloud:      hcloud"
            echo "  Container:  peelbox"
            echo "  Platform:   appbahn"
            echo "  Task:       go-task"
            echo "  Utils:      yq, dos2unix, pre-commit"
            echo ""
          '';
        };
      }
    );
}
