apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: larapaper-secret
  namespace: larapaper
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: larapaper-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: larapaper
        property: app_key
