apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: artifact-keeper-db
  namespace: artifact-keeper
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    size: 15Gi
    storageClass: ceph-block
  monitoring:
    enablePodMonitor: true
  postgresql:
    parameters:
      max_slot_wal_keep_size: "2GB"
  bootstrap:
    initdb:
      database: artifact_registry
      owner: registry
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: dependency-track
  namespace: artifact-keeper
spec:
  cluster:
    name: artifact-keeper-db
  name: dependency_track
  owner: registry
