apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-backup-yggdrasil-creds
  namespace: artifact-keeper
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: cnpg-backup-yggdrasil-creds
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: yggdrasil-s3
        property: access_key
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: yggdrasil-s3
        property: secret_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-backup-wasabi-creds
  namespace: artifact-keeper
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: cnpg-backup-wasabi-creds
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: wasabi
        property: access_key
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: wasabi
        property: secret_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: artifact-keeper-secrets
  namespace: artifact-keeper
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: artifact-keeper-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        JWT_SECRET: "{{`{{ .password }}`}}"
        SSO_ENCRYPTION_KEY: "{{`{{ .sso_encryption_key }}`}}"
        DEPENDENCY_TRACK_API_KEY: "{{`{{ .dtrack_api_key }}`}}"
  data:
    - secretKey: password
      remoteRef:
        key: artifact-keeper
        property: jwt_secret
    - secretKey: sso_encryption_key
      remoteRef:
        key: artifact-keeper
        property: sso_encryption_key
    - secretKey: dtrack_api_key
      remoteRef:
        key: artifact-keeper
        property: dtrack_api_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: artifact-keeper-zitadel
  namespace: artifact-keeper
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: artifact-keeper-zitadel
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client_id
      remoteRef:
        key: zitadel/artifact_keeper-credentials
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: zitadel/artifact_keeper-credentials
        property: client_secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dtrack-zitadel
  namespace: artifact-keeper
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: dtrack-zitadel
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client_id
      remoteRef:
        key: zitadel/dtrack-credentials
        property: client_id
