apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: readur-pg
  namespace: readur
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  storage:
    size: 5Gi
  monitoring:
    enablePodMonitor: true
  postgresql:
    parameters:
      max_slot_wal_keep_size: "2GB"
  bootstrap:
    initdb:
      database: readur
      owner: readur
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      enabled: true
      isWALArchiver: true
      parameters:
        barmanObjectName: yggdrasil-store
