apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-barman-cloud-plugin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://cloudnative-pg.github.io/charts
    chart: plugin-barman-cloud
    targetRevision: 0.5.0
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudnative-pg
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
