apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: default
  ignoreDifferences:
    - group: '*'
      jqPathExpressions:
        - .data."admin-user"
        - .data."admin-password"
      kind: Secret
    - group: '*'
      jqPathExpressions:
        - .metadata.annotations."gethomepage.dev/widget.password"
      kind: Ingress
  source:
    repoURL: ghcr.io/grafana/helm-charts
    targetRevision: 5.22.1
    chart: grafana-operator
    helm:
      valuesObject:
        serviceMonitor:
          enabled: true
        dashboard:
          enabled: true
        extraObjects:
          - apiVersion: external-secrets.io/v1
            kind: ExternalSecret
            metadata:
              name: "oauth-secret"
            spec:
              secretStoreRef:
                name: openbao-store
                kind: ClusterSecretStore
              refreshInterval: "1h"
              target:
                name: oauth-secret
                creationPolicy: 'Owner'
                deletionPolicy: "Retain"
                template:
                  type: Opaque
                  data:
                    client-id: "{{`{{ .client_id }}`}}"
                    client-secret: "{{`{{ .client_secret }}`}}"
              data:
                - secretKey: client_id
                  remoteRef:
                    key: zitadel/grafana-credentials
                    property: client_id
                - secretKey: client_secret
                  remoteRef:
                    key: zitadel/grafana-credentials
                    property: client_secret
          - apiVersion: grafana.integreatly.org/v1beta1
            kind: Grafana
            metadata:
              name: grafana
              labels:
                dashboards: "grafana"
            spec:
              persistentVolumeClaim:
                spec:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 1Gi
                  storageClassName: ceph-block
              deployment:
                spec:
                  revisionHistoryLimit: 1
                  template:
                    spec:
                      containers:
                        - name: grafana
                          env:
                            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
                              valueFrom:
                                secretKeyRef:
                                  name: oauth-secret
                                  key: client-id
                            - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
                              valueFrom:
                                secretKeyRef:
                                  name: oauth-secret
                                  key: client-secret
                          securityContext:
                            runAsNonRoot: false
                            runAsUser: 0
                          readinessProbe:
                            failureThreshold: 3
                      volumes:
                        - name: grafana-data
                          persistentVolumeClaim:
                            claimName: grafana-pvc
                  strategy:
                    type: Recreate
              config:
                server:
                  domain: "grafana.kirillorlov.pro"
                  root_url: "https://grafana.kirillorlov.pro"
                auth:
                  disable_gravatar: "true"
                  disable_login_form: "true"
                  disable_signout_menu: "false"
                  disable_user_sign_up: "false"
                  oauth_allow_insecure_email_lookup: "true"
                log:
                  mode: "console"
                auth.generic_oauth:
                  enabled: "true"
                  name: "Homelab"
                  allow_sign_up: "true"
                  use_pkce: "true"
                  client_id: "$__env{GF_AUTH_GENERIC_OAUTH_CLIENT_ID}"
                  client_secret: "$__env{GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}"
                  scopes: "openid email profile"
                  email_attribute_path: "email"
                  login_attribute_path: "preferred_username"
                  name_attribute_path: "name"
                  auth_url: "https://auth.kirillorlov.pro/oauth/v2/authorize"
                  token_url: "https://auth.kirillorlov.pro/oauth/v2/token"
                  api_url: "https://auth.kirillorlov.pro/oidc/v1/userinfo"
                  role_attribute_path: "'Admin'"
                  skip_org_role_sync: "true"
              ingress:
                metadata:
                  annotations:
                    cert-manager.io/cluster-issuer: "acme-issuer"
                    gethomepage.dev/enabled: "true"
                    gethomepage.dev/href: "https://grafana.kirillorlov.pro"
                    gethomepage.dev/group: Cluster Management
                    gethomepage.dev/name: Grafana
                    gethomepage.dev/icon: grafana.png
                    gethomepage.dev/pod-selector: "app=grafana"
                    gethomepage.dev/widget.type: grafana
                    gethomepage.dev/widget.url: https://grafana.kirillorlov.pro/
                    gethomepage.dev/widget.username: "$GF_SECURITY_ADMIN_USER$"
                    gethomepage.dev/widget.password: "$GF_SECURITY_ADMIN_PASSWORD$"
                    kirillorlov.pro/annotationsFromSecretName: grafana-admin-credentials
                spec:
                  ingressClassName: traefik
                  rules:
                    - host: grafana.kirillorlov.pro
                      http:
                        paths:
                          - backend:
                              service:
                                name: grafana-service
                                port:
                                  number: 3000
                            path: /
                            pathType: Prefix
                  tls:
                    - hosts:
                        - grafana.kirillorlov.pro
                      secretName: grafana-tls-secret
          - apiVersion: grafana.integreatly.org/v1beta1
            kind: GrafanaDatasource
            metadata:
              name: prometheus-grafanadatasource
            spec:
              datasource:
                access: "proxy"
                type: prometheus
                name: Prometheus
                isDefault: true
                url: http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090
              instanceSelector:
                matchLabels:
                  dashboards: grafana
          - apiVersion: grafana.integreatly.org/v1beta1
            kind: GrafanaDatasource
            metadata:
              name: victoriametrics-grafanadatasource
            spec:
              datasource:
                access: "proxy"
                type: prometheus
                name: VictoriaMetrics
                url: http://vmsingle-main.victoriametrics.svc.cluster.local:8429
              instanceSelector:
                matchLabels:
                  dashboards: grafana
          - apiVersion: grafana.integreatly.org/v1beta1
            kind: GrafanaDatasource
            metadata:
              name: victorialogs-grafanadatasource
            spec:
              datasource:
                access: "proxy"
                type: victoriametrics-logs-datasource
                name: Victoria Logs
                url: http://victorialogs-victoria-logs-single-server.victorialogs.svc.cluster.local:9428
              instanceSelector:
                matchLabels:
                  dashboards: grafana
              plugins:
                - name: victoriametrics-logs-datasource
                  version: 0.16.3
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
