apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubescape
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubescape.github.io/helm-charts
    chart: kubescape-operator
    targetRevision: 1.30.6
    helm:
      valuesObject:
        clusterName: homelab
        capabilities:
          continuousScan: enable
          vulnerabilityScan: enable
          nodeScan: enable
        persistence:
          storageClass: "ceph-block"

  ignoreDifferences:
    - group: ''
      kind: Secret
      jqPathExpressions:
        - '.data'
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jqPathExpressions:
        - '.webhooks[]?.clientConfig.caBundle'
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - '.spec.conversion'
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jqPathExpressions:
        - '.metadata.annotations'
    - group: apiregistration.k8s.io
      kind: APIService
      jqPathExpressions:
        - '.spec.caBundle'
    - group: batch
      kind: CronJob
      jqPathExpressions:
        - '.spec.schedule'
  destination:
    server: https://kubernetes.default.svc
    namespace: kubescape
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
