apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-cleanup-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-cleanup-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-cleanup-operator
    repoURL:  https://charts.lwolf.org/
    targetRevision: 1.0.4
    helm:
       valuesObject:
         rbac:
           global: true
         serviceMonitor:
           enabled: true
         args:
           - --delete-successful-after=15m
           - --delete-failed-after=120m
           - --delete-pending-pods-after=60m
           - --delete-evicted-pods-after=60m
           - --delete-orphaned-pods-after=60m
           - --legacy-mode=false
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
