apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: opentelemetry-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: opentelemetry-operator
    repoURL: ghcr.io/open-telemetry/opentelemetry-helm-charts
    targetRevision: 0.109.0
    helm:
      values: |
        admissionWebhooks:
          certManager:
            enabled: true
        manager:
          collectorImage:
            repository: otel/opentelemetry-collector-contrib
          serviceMonitor:
            enabled: true
          createRbacPermissions: true
          prometheusRule:
            enabled: true 
            defaultRules:
              enabled: true
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
