# Harbor — replaces artifact-keeper as the private container registry.
#
# The Harbor provider talks to the live Harbor API, so the resources below can
# only apply once Harbor is deployed and reachable at https://harbor.kirillorlov.pro.
# On a clean bootstrap, create the prerequisites first so the in-cluster
# ExternalSecret can resolve and Harbor can start:
#   tofu apply -target=vault_kv_secret_v2.harbor \
#              -target=zitadel_application_oidc.harbor \
#              -target=vault_kv_secret_v2.zitadel_credentials
# then deploy the chart, then a plain `tofu apply` to configure OIDC + projects.

# --- Generated credentials, stored in OpenBao for the ExternalSecret ----------
resource "random_password" "harbor_admin" {
  length  = 24
  special = false
}

# Harbor's `secretKey` must be exactly 16 chars and stable for the lifetime of
# the data (it encrypts stored registry credentials at rest).
resource "random_password" "harbor_secret_key" {
  length  = 16
  special = false
}

resource "vault_kv_secret_v2" "harbor" {
  mount = "secret"
  name  = "harbor"

  data_json = jsonencode({
    admin_password = random_password.harbor_admin.result
    secret_key     = random_password.harbor_secret_key.result
  })
}

# --- Zitadel OIDC client (creds land in OpenBao via the shared map in zitadel.tf)
resource "zitadel_application_oidc" "harbor" {
  org_id                      = var.zitadel_org_id
  project_id                  = zitadel_project.homelab.id
  name                        = "Harbor"
  redirect_uris               = ["https://harbor.kirillorlov.pro/c/oidc/callback"]
  post_logout_redirect_uris   = ["https://harbor.kirillorlov.pro"]
  response_types              = ["OIDC_RESPONSE_TYPE_CODE"]
  grant_types                 = ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE"]
  app_type                    = "OIDC_APP_TYPE_WEB"
  auth_method_type            = "OIDC_AUTH_METHOD_TYPE_BASIC"
  version                     = "OIDC_VERSION_1_0"
  access_token_type           = "OIDC_TOKEN_TYPE_JWT"
  access_token_role_assertion = true
  id_token_role_assertion     = true
  id_token_userinfo_assertion = true
}

# --- Harbor API configuration -------------------------------------------------
provider "harbor" {
  url      = "https://harbor.kirillorlov.pro"
  username = "admin"
  password = random_password.harbor_admin.result
}

# Point Harbor at Zitadel for SSO. auto_onboard creates Harbor users on first
# OIDC login; user_claim maps the Harbor username to the preferred_username.
resource "harbor_config_auth" "oidc" {
  auth_mode          = "oidc_auth"
  primary_auth_mode  = true
  oidc_name          = "Zitadel"
  oidc_endpoint      = "https://auth.kirillorlov.pro"
  oidc_client_id     = zitadel_application_oidc.harbor.client_id
  # Write-only: never persisted to state. Bump the version to push a rotated
  # secret (e.g. after recreating the Zitadel app).
  oidc_client_secret_wo         = zitadel_application_oidc.harbor.client_secret
  oidc_client_secret_wo_version = 1
  oidc_scope         = "openid,profile,email,offline_access"
  oidc_user_claim    = "preferred_username"
  oidc_auto_onboard  = true
  oidc_verify_cert   = true
}

# Default "library" project, made public. Public => anonymous PULL is allowed.
# NOTE: Harbor has no anonymous push — writing always needs auth (admin or a
# robot account with push on this project). "library" is created by Harbor at
# install, so adopt it once with:
#   tofu import harbor_project.library /projects/1
resource "harbor_project" "library" {
  name   = "library"
  public = true
}

# Robot account for automated push/pull to the library project (the secret is
# generated by Harbor and exposed as a computed, sensitive attribute).
resource "harbor_robot_account" "library" {
  name        = "library-ci"
  description = "Automated push/pull for the library project"
  level       = "project"

  permissions {
    kind      = "project"
    namespace = harbor_project.library.name

    access {
      action   = "push"
      resource = "repository"
    }
    access {
      action   = "pull"
      resource = "repository"
    }
  }
}

# Stash the robot creds in OpenBao so workloads/CI can build a docker login or
# an imagePullSecret from them. full_name looks like robot$library+library-ci.
resource "vault_kv_secret_v2" "harbor_robot_library" {
  mount = "secret"
  name  = "harbor-robot-library"

  data_json = jsonencode({
    username = harbor_robot_account.library.full_name
    password = harbor_robot_account.library.secret
  })
}

# --- Pull-through proxy registries ------------------------------------------
# Six upstream registries used by this cluster (verified from
# `kubectl get pods -A -o json` image inventory). Each pair is a
# `harbor_registry` (the upstream endpoint config) + `harbor_project`
# (the cache project, public so Talos containerd can pull anonymously).
#
# Talos's `machine.registries.mirrors` block (talos/talconfig.yaml) routes
# image pulls to `harbor.kirillorlov.pro/v2/<project>/...` with
# `overridePath: true`. Harbor's token endpoint properly handles multi-scope
# Bearer requests, so containerd's two-scope auth flow that broke against
# artifact-keeper works here.

# Upstream registry credentials. harbor_registry.access_secret is a regular
# state-persisted attribute (no _wo alternative in the harbor provider), so
# these come in as TF_VARs from OpenBao (exported by flake.nix) rather than
# deprecated vault data sources.
variable "dockerhub_username" {
  description = "Docker Hub username (OpenBao secret/dockerhub; exported by flake.nix)"
  type        = string
}

variable "dockerhub_pat" {
  description = "Docker Hub PAT (OpenBao secret/dockerhub; exported by flake.nix)"
  type        = string
  sensitive   = true
}

variable "github_pat" {
  description = "GitHub PAT with read:packages for GHCR (OpenBao secret/github; exported by flake.nix)"
  type        = string
  sensitive   = true
}

variable "quay_username" {
  description = "quay.io robot username (OpenBao secret/quay; exported by flake.nix)"
  type        = string
}

variable "quay_token" {
  description = "quay.io robot token (OpenBao secret/quay; exported by flake.nix)"
  type        = string
  sensitive   = true
}

# Docker Hub — wired with a PAT so we don't blow through the 100/6h
# unauthenticated rate limit.
resource "harbor_registry" "docker_hub" {
  name          = "docker-hub-upstream"
  provider_name = "docker-hub"
  endpoint_url  = "https://hub.docker.com"
  access_id     = var.dockerhub_username
  access_secret = var.dockerhub_pat
}

resource "harbor_project" "docker_hub" {
  name          = "docker-hub"
  public        = true
  registry_id   = harbor_registry.docker_hub.registry_id
  storage_quota = 50
}

# GHCR — even public packages need an anonymous bearer token, which Harbor's
# proxy won't negotiate without creds. Authenticate with a GitHub PAT
# (read:packages) via the generic docker-registry adapter (basic->token auth).
# Username is just the GitHub handle.
resource "harbor_registry" "ghcr" {
  name          = "ghcr-upstream"
  provider_name = "docker-registry"
  endpoint_url  = "https://ghcr.io"
  access_id     = "diverofdark"
  access_secret = var.github_pat
}

resource "harbor_project" "ghcr" {
  name          = "ghcr"
  public        = true
  registry_id   = harbor_registry.ghcr.registry_id
  storage_quota = 50
}

# Quay (Red Hat / Cilium / etc.). Harbor's "quay" adapter doesn't support
# proxy-cache, and quay.io needs an anonymous bearer token. Use the generic
# docker-registry adapter with a quay.io robot token (read-only). Create a
# robot under any quay.io account and store it in OpenBao secret/quay with
# properties: username (e.g. <account>+<robot>) and token.
resource "harbor_registry" "quay" {
  name          = "quay-upstream"
  provider_name = "docker-registry"
  endpoint_url  = "https://quay.io"
  access_id     = var.quay_username
  access_secret = var.quay_token
}

resource "harbor_project" "quay" {
  name          = "quay"
  public        = true
  registry_id   = harbor_registry.quay.registry_id
  storage_quota = 50
}

# registry.k8s.io — Kubernetes core images (kube-apiserver, coredns,
# csi-snapshotter, etc.). No auth.
resource "harbor_registry" "registry_k8s" {
  name          = "registry-k8s-upstream"
  provider_name = "docker-registry"
  endpoint_url  = "https://registry.k8s.io"
}

resource "harbor_project" "registry_k8s" {
  name          = "registry-k8s"
  public        = true
  registry_id   = harbor_registry.registry_k8s.registry_id
  storage_quota = 50
}

# public.ecr.aws — Amazon ECR Public
resource "harbor_registry" "ecr_public" {
  name          = "ecr-public-upstream"
  provider_name = "docker-registry"
  endpoint_url  = "https://public.ecr.aws"
}

resource "harbor_project" "ecr_public" {
  name          = "ecr-public"
  public        = true
  registry_id   = harbor_registry.ecr_public.registry_id
  storage_quota = 20
}

# reg.kyverno.io — Kyverno's own registry
resource "harbor_registry" "kyverno" {
  name          = "kyverno-upstream"
  provider_name = "docker-registry"
  endpoint_url  = "https://reg.kyverno.io"
}

resource "harbor_project" "kyverno" {
  name          = "kyverno"
  public        = true
  registry_id   = harbor_registry.kyverno.registry_id
  storage_quota = 10
}
