apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: phos-zitadel
  namespace: phos
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  refreshInterval: "10s"
  target:
    name: phos-zitadel
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client_id
      remoteRef:
        key: zitadel/phos-credentials
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: zitadel/phos-credentials
        property: client_secret
