apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "nextcloud-secret"
  namespace: nextcloud
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: nextcloud-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        WIDGET_KEY: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: pihole
        property: password
---
