# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, inputs, ... }:

{
  # Use the extlinux boot loader. (NixOS wants to enable GRUB by default)
  boot.loader.grub.enable = false;
  # Enables the generation of /boot/extlinux/extlinux.conf
  boot.loader.generic-extlinux-compatible.enable = true;

  boot.initrd.availableKernelModules = [ "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.kernelParams = [
    "console=ttyS1,115200n8"
  ];
  boot.extraModulePackages = [ ];
  hardware.enableRedistributableFirmware = true;

  hardware.firmware = [ pkgs.raspberrypiWirelessFirmware ];
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/44444444-4444-4444-8888-888888888888";
      fsType = "ext4";
    };
  
  networking.interfaces.enu1u1.useDHCP = lib.mkForce false;
  networking.interfaces.enu1u1.ipv4.addresses = [ {
    address = "192.168.178.2";
    prefixLength = 24;
  } ];
  networking.defaultGateway = "192.168.178.1";
  networking.nameservers = [ "127.0.0.1" ];

  swapDevices = [ {
    device = "/swapfile";
    size = 2048;
  } ];

  services.adguardhome = {
    enable = true;
    settings = {
      bind_port = 80;
    };
    openFirewall = true;
    allowDHCP = true;
  };

  networking.firewall.enable = false;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkForce false;
  # networking.interfaces.enu1u1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlan0.useDHCP = lib.mkDefault true;
  
  age.secrets.wifipassword.file = secrets/wifipassword.age; 
  
  networking.hostName = "ratatoskr";
  networking.wireless = {
    enable = false;
    environmentFile = config.age.secrets.wifipassword.path;
    networks = {
      DeepWiFi = {
        psk = "@WIFI_PASS@";
      };
    };
  };
  networking.enableIPv6 = false;
  environment = {
    systemPackages = with pkgs; [
      libraspberrypi 
      iw
    ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";

  hardware.wirelessRegulatoryDatabase = true;
  boot.extraModprobeConfig = ''
    options cfg80211 ieee80211_regdom="DE"
  '';
}