# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, nixpkgs-wsl, ... }:

{
  imports = [
          #<nixpkgs-wsl/modules>
    # include NixOS-WSL modules
  ];
  networking.hostName = "archerwsl";
  wsl.enable = true;
  wsl.defaultUser = "nixos";
}
