# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, nixpkgs-wsl, ... }:

{
  networking.hostName = "archerwsl";
  wsl.enable = true;
  wsl.defaultUser = "nixos";
  wsl.interop.register = true;

  virtualisation.docker.enable = true;
  users.extraGroups.docker.members = [ "diverofdark" "nixos" ];

  nix = {
    optimise.automatic = lib.mkForce false;
    gc = {
      automatic = lib.mkForce false;
    };
  };
}
