apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: inker-secret
  namespace: inker
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: inker-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ADMIN_PIN
      remoteRef:
        key: inker
        property: admin_pin
