apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: terminus-secret
  namespace: terminus
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: terminus-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: APP_SECRET
      remoteRef:
        key: terminus
        property: app_secret
