apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actualbudget
  namespace: actualbudget
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: actualbudget
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        password: "{{ .password }}"
        apikey: "{{ .apikey }}"
  data:
    - secretKey: password
      remoteRef:
        key: actualbudget
        property: password
    - secretKey: apikey
      remoteRef:
        key: pihole
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actualbudget-zitadel
  namespace: actualbudget
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: actualbudget-zitadel
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: client_id
      remoteRef:
        key: zitadel/actual_budget-credentials
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: zitadel/actual_budget-credentials
        property: client_secret