apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trmnl-cyberpunk
  namespace: trmnl-cyberpunk
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: trmnl-cyberpunk
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: TRMNL_API_KEY
      remoteRef:
        key: trmnl-cyberpunk
        property: api_key
