apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zitadel-machinekey
  namespace: zitadel
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: zitadel-machinekey
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        masterkey: "{{ .masterkey }}"
  data:
    - secretKey: masterkey
      remoteRef:
        key: zitadel/masterkey
        property: masterkey
