apiVersion: v1
kind: ConfigMap
metadata:
  name: hook-extension
  namespace: github-runner
data:
  template.yaml: |
    spec:
      containers:
        - name: $job
          env:
            - name: DOCKER_HOST
              value: tcp://shared-dind.github-runner.svc:2375
            - name: TESTCONTAINERS_HOST_OVERRIDE
              value: shared-dind.github-runner.svc