apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-runner-instance-peelbox
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/actions/actions-runner-controller-charts
    targetRevision: 0.14.0
    chart: gha-runner-scale-set
    helm:
      valuesObject:

        githubConfigUrl: "https://github.com/diverofdark/peelbox"

        githubConfigSecret: github-secret

        maxRunners: 5
        minRunners: 1
        controllerServiceAccount:
          name: "github-runner-controller-gha-rs-controller"
          namespace: "github-runner-instance-peelbox"

        template:
          spec:
            restartPolicy: Never
            containers:
              - name: runner
                image: ghcr.io/actions/actions-runner:latest
                command: ["/home/runner/run.sh"]
                env:
                  - name: DOCKER_HOST
                    value: unix:///var/run/docker.sock
                volumeMounts:
                  - name: work
                    mountPath: /home/runner/_work
                  - name: dind-sock
                    mountPath: /var/run
              - name: dind
                image: docker:dind
                securityContext:
                  privileged: true
                volumeMounts:
                  - name: work
                    mountPath: /home/runner/_work
                  - name: dind-sock
                    mountPath: /var/run
                  - name: dind-storage
                    mountPath: /var/lib/docker
            volumes:
              - name: work
                emptyDir: {}
              - name: dind-sock
                emptyDir: {}
              - name: dind-storage
                emptyDir:
                  sizeLimit: 75Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: github-runner
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged