apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "github-secret"
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: github-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        github_token: "{{ .pat }}"
  data:
    - secretKey: pat
      remoteRef:
        key: github
        property: pat
---