apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plex-secret
  namespace: media
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: plex-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        JELLYSEERR_TOKEN: "{{ .jellyseerrApiKey }}"
        RADARR_API_KEY: "{{ .radarrApiKey }}"
        SONARR_API_KEY: "{{ .sonarrApiKey }}"
  data:
    - secretKey: jellyseerrApiKey
      remoteRef:
        key: jellyseerr
        property: api_key
    - secretKey: sonarrApiKey
      remoteRef:
        key: sonarr
        property: api_key
    - secretKey: radarrApiKey
      remoteRef:
        key: radarr
        property: api_key
---