apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: rsstt-pg
  namespace: rss-telegram-bot
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: rsstt
      owner: rsstt
