apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "pihole-password"
  namespace: external-dns
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: pihole-password
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        EXTERNAL_DNS_PIHOLE_PASSWORD: '{{ .password }}'
  data:
    - secretKey: password
      remoteRef:
        key: pihole
        property: password
---