apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-exporter
  namespace: external-dns
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: pihole-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pihole-exporter
    spec:
      containers:
        - name: pihole-exporter
          image: ekofr/pihole-exporter:v1.2.0
          env:
            - name: PIHOLE_HOSTNAME
              value: "192.168.178.2"
            - name: PIHOLE_PROTOCOL
              value: "http"
            - name: PIHOLE_PORT
              value: "80"
            - name: PORT
              value: "9617"
            - name: INTERVAL
              value: "30s"
            - name: PIHOLE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pihole-password
                  key: PIHOLE_PASSWORD
          ports:
            - name: http
              protocol: TCP
              containerPort: 9617
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 6
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-exporter
  namespace: external-dns
  labels:
    app.kubernetes.io/name: pihole-exporter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pihole-exporter
  ports:
    - name: http
      port: 9617
      targetPort: http
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pihole-exporter
  namespace: external-dns
  labels:
    app.kubernetes.io/name: pihole-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pihole-exporter
  endpoints:
    - port: http
      path: /metrics
      interval: 60s
      scrapeTimeout: 30s
