apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "argocd-readonly-token"
  namespace: argocd
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  refreshInterval: "1h"
  target:
    name: argocd-readonly-token
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        token: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: argocd-readonly
        property: token
---