apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "prometheus-external-secret"
  namespace: prometheus
spec:
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore

  refreshInterval: "10s"

  target:
    name: prometheus-grafana
    creationPolicy: 'Owner'
    deletionPolicy: "Retain"
    template:
      type: Opaque
      data:
        admin-user: "{{ .admin_user }}"
        admin-password: "{{ .admin_password }}"
        ldap-toml: ""

  data:
    - secretKey: admin_user
      remoteRef:
        key: grafana/admin
        property: admin_user
    - secretKey: admin_password
      remoteRef:
        key: grafana/admin
        property: admin_password
---
