name: Homelab CI/CD

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  validate:
    name: Validate
    runs-on: github-runner-instance
    container: buildpack-deps:trixie
    steps:
      - uses: actions/checkout@v6
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: DeterminateSystems/determinate-nix-action@v3.17.1
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Generate and validate configs
        env:
          BAO_TOKEN: ${{ secrets.OPENBAO_TOKEN }}
          KUBERNETES_SERVICE_HOST: kubernetes.default.svc
          KUBERNETES_SERVICE_PORT: 443
        run: |
          nix develop --command bash -euxo pipefail -c '
            pushd talos
            task genconfig
            task validate
            popd

            pushd terraform
            unset TF_VAR_kube_config
            unset KUBE_CONFIG_PATH

            tofu init
            tofu plan -lock=false
          '

  apply:
    name: Apply
    concurrency:
      group: apply
      cancel-in-progress: true
    needs:
      - validate
    runs-on: github-runner-instance
    container: buildpack-deps:trixie
    if: github.ref == 'refs/heads/master'
    environment:
      name: Homelab
    steps:
      - uses: actions/checkout@v6
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: DeterminateSystems/determinate-nix-action@v3.17.1
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Apply configs
        env:
          BAO_ADDR: http://openbao-active.openbao.svc.cluster.local:8200
          BAO_TOKEN: ${{ secrets.OPENBAO_TOKEN }}

          TF_VAR_openbao_token: ${{ secrets.OPENBAO_TOKEN }}
          TF_CLI_ARGS_init: "-backend-config=config.kubernetes.tfbackend"
          KUBERNETES_SERVICE_HOST: kubernetes.default.svc
          KUBERNETES_SERVICE_PORT: 443
        run: |
          nix develop --command bash -euxo pipefail -c '
            pushd talos
            task genconfig
            talhelper gencommand apply --out-dir ./clusterconfig | bash
            popd

            pushd terraform
            tofu init
            tofu apply -auto-approve
            popd
          '