name: Homelab CI/CD

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    name: Validate
    runs-on: github-runner-instance
    container: buildpack-deps:trixie
    steps:
      - uses: actions/checkout@v6
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: DeterminateSystems/determinate-nix-action@v3.17.1
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Generate and validate configs
        env:
          BAO_TOKEN: ${{ secrets.OPENBAO_TOKEN }}
        run: |
          nix develop --command bash -euxo pipefail -c '
            pushd talos
            task genconfig
            task validate
            popd

            pushd terraform
            tofu init
            tofu plan -lock=false
          '

  apply:
    name: Apply
    concurrency:
      group: apply
      cancel-in-progress: true
    needs:
      - validate
    runs-on: github-runner-instance
    container: buildpack-deps:trixie
    if: github.ref == 'refs/heads/master'
    environment:
      name: Homelab
    steps:
      - uses: actions/checkout@v6
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: DeterminateSystems/determinate-nix-action@v3.17.1
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Apply configs
        env:
          BAO_TOKEN: ${{ secrets.OPENBAO_TOKEN }}
        run: |
          nix develop --command bash -euxo pipefail -c '
            pushd talos
            task apply --yes
            popd

            pushd terraform
            tofu init
            tofu apply -auto-approve
            popd
          '